
$manager_script = <<SCRIPT
echo Swarm Init...
sudo docker swarm init --listen-addr 192.168.56.10:2377 --advertise-addr 192.168.56.10:2377
sudo docker swarm join-token --quiet worker > /vagrant/worker_token
SCRIPT
$worker_script = <<SCRIPT
echo Swarm Join...
sudo docker swarm join --token $(cat /vagrant/worker_token) 192.168.56.10:2377
SCRIPT

Vagrant.configure('2') do |config|
  vm_box = 'ubuntu/focal64'
  config.vm.define :manager, primary: true  do |manager|
      manager.vm.box = vm_box
      manager.vm.box_check_update = true
      manager.vm.network :private_network, ip: "192.168.56.10"

      manager.vagrant.plugins = "vagrant-docker-compose"
      manager.vm.provision :docker
      manager.vm.provision :docker_compose

      manager.vm.hostname = "manager"
      manager.vm.synced_folder ".", "/vagrant"

      manager.vm.provision "shell", inline: $manager_script, privileged: true
      manager.vm.provider "virtualbox" do |vb|
        vb.name = "manager"
        vb.memory = "1024"
      end
    end
  (1..2).each do |i|
      config.vm.define "worker0#{i}" do |worker|
        worker.vm.box = vm_box
        worker.vm.box_check_update = true
        worker.vm.network :private_network, ip: "192.168.56.1#{i}"

        worker.vagrant.plugins = "vagrant-docker-compose"
        worker.vm.provision :docker
        worker.vm.provision :docker_compose

        worker.vm.hostname = "worker0#{i}"
        worker.vm.synced_folder ".", "/vagrant"

        worker.vm.provision "shell", inline: $worker_script, privileged: true
        worker.vm.provider "virtualbox" do |vb|
          vb.name = "worker0#{i}"
          vb.memory = "1024"
        end
      end
    end
  end
