### Health check
GET http://localhost:8080/diag/health


### List all todos
GET http://localhost:8080/todos

### Add todo
POST http://localhost:8080/todos

{
    "title": "Rocking todo",
    "description": "Nice, fancy description because we can add it"
}


### Health check on minikube
GET http://192.168.49.2:8080/diag/health


