GET http://localhost:8080/api/v1/bikes

###

GET http://localhost:8080/api/v1/bikes/1

###

POST http://localhost:8080/api/v1/bikes
content-type: application/json

{
  "name": "test bike",
  "email": "test@test.com",
  "phone": "+36101234567",
  "model": "two wheels bike",
  "serialNumber": "123-WQW",
  "purchasePrice": 120000,
  "purchaseDate": "2020-09-08",
  "contact": false
}
###